// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a7045edf-40b7-4195-81d2-5254ddd46239",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KCmS3v0JD",
    "aws_user_pools_web_client_id": "2ci6vck4hs6p26n578k5pp4j8j",
    "oauth": {}
};


export default awsmobile;
